### ISSUE TITLE
let's add a LICENCE file

### ISSUE THREAD

**Issue by revelt** [equinusocio/xity-starter#14]
Users can see we're under MIT license but we don't have a standalone file in the root. What do you think about adding one?

**Comment by d2s** [comment]
Partly makes sense, but wondering whether putting the license file there will cause more harm in the long run. Problem is that people will build on top of this project template, and might accidentally license their (personal or work) projects under MIT license without understanding the effects of it.

Separate issue, but as [npm documentation](https://docs.npmjs.com/files/package.json#license "npm-package.json | npm Documentation") says, we should consider also setting `"private": true` for the `package.json` file to prevent accidental publication of a website as a npm package.

**Comment by revelt** [comment]
It makes sense. I'll close. Feel free to reopen.

**Comment by equinusocio** [comment]
> Separate issue, but as npm documentation says, we should consider also setting "private": true for the package.json file to prevent accidental publication of a website as a npm package.

I've missed it. Done.
