### ISSUE TITLE
Cache busting

### ISSUE THREAD

**Issue by revelt** [equinusocio/xity-starter#20]
Would maintainers consider implementing cache-busting?

I'm asking because I've implemented a rudimentary folder-based timestamp cache busting on my XITY-based project and it seemed a pretty advanced job.

I'm not using service workers which surely adds even more considerations caching-wise.

What do you guys think?

**Comment by equinusocio** [comment]
Do you mean adding cache-busting in place of the service-worker?

**Comment by revelt** [comment]
Sorry for ignorance my part, it seems current `eleventy-plugin-pwa` is using `workbox` so cache-busting should be automated. I'm a bit cautious because the plugin still looks like a black box to me. I'll close.
