### ISSUE TITLE
Pre-installed Netlify CMS

### ISSUE THREAD

**Issue by rahxuls** [equinusocio/xity-starter#23]

**Comment by equinusocio** [comment]
Hello! At the moment we don't want to bind the XITY to a specific cms that may be useless to many users. For example Forestry is another good cms that can be added easily by following its wizard. 

If you want, you can write a tut about adding Netlify CSS to XITY starter and we'll be happy to add/link them to the readme

**Comment by equinusocio** [comment]
1.
