### ISSUE TITLE
Error upon dev

### ISSUE THREAD

**Issue by djmtype** [equinusocio/xity-starter#24]
Getting this error with `yarn dev`: 

```
@parcel/transformer-postcss: Could not resolve package "postcss" that satisfies ^8.0.0. Found 7.0.35.
```

**Comment by djmtype** [comment]
This only happens when running `npx degit equinusocio/xity-starter#parcel` inside an empty directory. If I clone this repo instead, everything works.

**Comment by equinusocio** [comment]
Did you run `yarn` or `npm i` after the clone? The error is related to some dependency version

**Comment by djmtype** [comment]
@equinusocio `yarn install`

**Comment by equinusocio** [comment]
@djmtype Thank you, you can fix this by running `yarn add -D parcel@next`. The issue was caused by an old parcel v2 version. I'm pushing the change to the package.json right now.
