### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by 0xflotus** [equinusocio/xity-starter#27]
I would like to have a dark mode for this 11ty-starter :)

**Comment by equinusocio** [comment]
Yeah, this is something we can add. It would be implemented by using postcss-dark-theme-class plugin which makes this super easy to do.

**Comment by 0xflotus** [comment]
> Yeah, this is something we can add. It would be implemented by using postcss-dark-theme-class plugin which makes this super easy to do.

cool. Sounds great 🎉

**Comment by equinusocio** [comment]
@0xflotus I've released the XITY v2 which introduce a lot of changes and the theme switcher. Check the `main` branch.

**Comment by epnlespieux** [comment]
Hi,
First of all thanks for this 11ty starter template.
Seems that the theme switch is not working at all...

![image](https://user-images.githubusercontent.com/17499486/115007865-bd26d600-9eaa-11eb-980c-ca52f9553b37.png)

And the choice is not memorized when we go to another page.

**Comment by equinusocio** [comment]
> Hi,
> First of all thanks for this 11ty starter template.
> Seems that the theme switch is not working at all...
> 
> ![image](https://user-images.githubusercontent.com/17499486/115007865-bd26d600-9eaa-11eb-980c-ca52f9553b37.png)
> 
> And the choice is not memorized when we go to another page.

Hello, i pushed an update with the fix. Unfortunately I had to remove Turbolinks cause is deprecated.

**Comment by epnlespieux** [comment]
Thanks a lot ! Just discoverf Native Elements too ! seems to be very an interesting way to adopt.
