### ISSUE TITLE
Snowpack or Parcel?

### ISSUE THREAD

**Issue by bekharsky** [equinusocio/xity-starter#28]
Demo description says "Snowpack" bundler, but READ.ME claims Parcel. Will there be switch to Snowpack in future?

<img width="679" alt="Screenshot 2021-01-09 at 13 15 35" src="https://user-images.githubusercontent.com/832780/104090076-c46f8f80-527c-11eb-9126-4184e4dd4a25.png">

<img width="491" alt="Screenshot 2021-01-09 at 13 16 41" src="https://user-images.githubusercontent.com/832780/104090094-ebc65c80-527c-11eb-9104-98816de4863f.png">

**Comment by equinusocio** [comment]
We had a branch based on Snowpack but we closed it due to some issues between 11ty and snowpack. At the moment we support only Parcel 2.  

We’ll fix that inconsistency in doc

**Comment by equinusocio** [comment]
XITY v2 now lives under the main branch while the v1 is inside `parcel-deprecated` branch
