### ISSUE TITLE
The Native Elements

### ISSUE THREAD

**Issue by revelt** [equinusocio/xity-starter#44]
hi xity maintainers,

The Native Elements link which goes to `https://native-elements.stackblitz.io/` never finishes loading on my machine. When I google, there's only React Native elements popping up and articles from HTML6. Let's not play smart, let's explain thoroughly to people in the readme, what Native Elements are, _at what cost are they introduced here_ in xity and how to remove them. I've been making websites since 1998 and professionally since 2010 and I've never encountered "Native elements" in my client projects. It's not a common thing!

Let's not assume everybody knows what Native Elements are, let's either improve the readme or maybe consider removing N.E. altogether.

The main USP of xity is a solid build system — integration with snowpack out-of-the-box and _minimal_ framework you don't need to disassemble. Bare minimum. To me, it feels like Native Elements are a fancy extra.

If you disagree and feel free N.E. are a must, that's fine, close this ticket, no hurt feelings. 👍

**Comment by equinusocio** [comment]
Hello, the NE website has been moved and the link needs to be updated. Here the site:
https://native-elements.dev/#/

I think we should keep them in order to provide a basic style without a framework and which users can remove easily.

**Comment by revelt** [comment]
forgot to close, closing this ticket
