### ISSUE TITLE
Add CSS Modules

### ISSUE THREAD

**Issue by equinusocio** [equinusocio/xity-starter#8]
## Should css-modules be added to XITY?

The basic integration requires a new dev dependency ([posthtml](https://github.com/posthtml/posthtml)) and a new postcss-plugin that generate and extract css classes to pass to posthtml. CSS modules/component class should be add using the custom `css-module="classname"` instead of `class="classname"`.

## Example

give `header.pcss` file:

```pcss
.header {
   background-color: red;
}
```

`header.njk`
```html
<header css-module="header">....</header>
```

**output**
```css
.header-kjasdgf {
   background-color: red;
}
```
```html
<header class="header-kjasdgf"></header>
```

## Please vote!

- ❤️ if you want it by default
- 👎 if you don't want It by default

**Comment by d2s** [comment]
Is this really needed by default?
For a small scale website, such feature might create more issues instead of solving them.

**Comment by equinusocio** [comment]
@d2s Nope, is not needed, that's why I opened this.
